name: customer-churn
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - pip
  - pip:
    - -r file:requirements.txt

